myproject/urls.py
from django.conf.urls import patterns, include, url
from transactions.views import Index

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myproject.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    
    url(r'^$', Index.as_view(), name='index'),
    url(r'^transactions/api/', include('transactions.RESTurls')),
    url(r'^transactions/', include('transactions.urls')),
    url(r'^admin/', include(admin.site.urls)),
    #standad django login view
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='account-login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='account-logout'),
)

transactions/urls.py
from django.conf.urls import patterns, url
from transactions.views import *

urlpatterns = patterns('',
    #Shifts
    url(r'^shift/list/$', ShiftList.as_view(), name="shift-list"),
    url(r'^shift/details/(?P<pk>\d+)/$', ShiftDetail.as_view(), name='shift-detail'),
    url(r'^shift/create/$', CreateShift.as_view(), name='shift-new'),
    url(r'^shift/update/(?P<pk>\d+)/$', UpdateShift.as_view(), name='shift-update'),
    
    #Debtors 	
    url(r'^debtor/list/$', DebtorList.as_view(), name='debtor-list'),
    url(r'^debtor/debts/(?P<pk>\d+)/$', DebtorDebt.as_view(), name='debtor-debt'),
    url(r'^debtor/create/$', CreateDebtor.as_view(), name='debtor-new'),
    url(r'^debtor/update/(?P<pk>\d+)/$', UpdateDebtor.as_view(), name='debtor-update'),
    
    #Debts
    url(r'^debt/update/(?P<pk>\d+)/$', UpdateDebt.as_view(), name='debt-update'),
    url(r'^debt/details/(?P<pk>\d+)/$', DebtDetail.as_view(), name='debt-detail'),
    url(r'^debt/create/(?P<pk>\d+)/$', CreateDebt.as_view(), name='debt-new'),
    
    #Expenses 	
    url(r'^expense/list/$', ExpenseList.as_view(), name='expense-list'),
    url(r'^expense/create/$', CreateExpense.as_view(), name='expense-new'),
    url(r'^expense/update/(?P<pk>\d+)/$', UpdateExpense.as_view(), name='expense-update'),
    
    #Locations 	
    url(r'^location/list/$', LocationList.as_view(), name='location-list'),
    url(r'^location/create/$', CreateLocation.as_view(), name='location-new'),
    url(r'^location/update/(?P<pk>\d+)/$', UpdateLocation.as_view(), name='location-update'),
    
    #Operators 	
    url(r'^personnel/list/$', OperatorList.as_view(), name='personnel-list'),
    url(r'^personnel/create/$', CreatePersonnel.as_view(), name='personnel-new'),
    url(r'^personnel/update/(?P<pk>\d+)/$', UpdatePersonnel.as_view(), name='personnel-update'),
    
    #Payments 	
    url(r'^payment/update/(?P<pk>\d+)/$', UpdatePayment.as_view(), name='payment-update'),
    url(r'^payment/create/(?P<pk>\d+)/$', CreatePayment.as_view(), name='payment-new'),
    
    #Pays 
    url(r'^pay/list/$', PayList.as_view(), name='pay-list'),	
    url(r'^pay/create/$', CreatePay.as_view(), name='pay-new'),
    url(r'^pay/update/(?P<pk>\d+)/$', UpdatePay.as_view(), name='pay-update'),
    
    #Periods 	
    url(r'^period/list/$', PeriodList.as_view(), name="period-list"),
    url(r'^period/shifts/(?P<periodpk>\d+)/$', PeriodShifts.as_view(), name='period-shifts'),
    url(r'^period/details/(?P<pk>\d+)/$', PeriodDetail.as_view(), name='period-detail'),
    url(r'^period/create/$', CreatePeriod.as_view(), name='period-new'),
    url(r'^period/update/(?P<pk>\d+)/$', UpdatePeriod.as_view(), name='period-update'),
    
    #Emails
    url(r'^email/form/(?P<pk>\d+)/$', ContactFormView.as_view(), name='contact-form'),
    url(r'^email/form/(?P<pk>\d+)/sent/$', EmailSent.as_view(), name='email-sent'),
)

transactions/forms.py
from bootstrap3_datetime.widgets import DateTimePicker
from django import forms
from django.contrib.admin import widgets
from transactions.models import *

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
import floppyforms as forms

class ShiftForm(forms.ModelForm):
    shift_comments = forms.CharField(widget=forms.Textarea(attrs={'cols':50,'rows':15}))
    shift_from_date_and_time = forms.DateTimeField(widget=DateTimePicker(options={"format": "yyyy-mm-dd hh:mm","pickTime": True}))
    shift_to_date_and_time = forms.DateTimeField(widget=DateTimePicker(options={"format": "yyyy-mm-dd hh:mm","pickTime": True}))
                
    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        # now kwargs doesn't contain 'user', so we can safely pass it to the base class method
        super(ShiftForm, self).__init__(*args, **kwargs)
        self.fields['shift_period'].queryset = Period.objects.filter(created_by=user, paid = False)
        self.fields['shift_pay_rate'].queryset = Pay.objects.filter(created_by=user)
        
    class Meta:
        model = Shift
        exclude = ['shift_pay','shift_hours','created_by']

class PeriodForm(forms.ModelForm):
    class Meta:
        model = Period
        exclude = ['period_hours','personal_protection','period_pay','date_received', 'paid','period_week_ending_date','created_by']

class PeriodUpdateForm(forms.ModelForm):
    class Meta:
        model = Period
        exclude = ['created_by']

class ShiftUpdateForm(forms.ModelForm):
    class Meta:
        model = Shift
        exclude = ['created_by']

class PayUpdateForm(forms.ModelForm):
    class Meta:
        model = Pay
        exclude = ['created_by']

class ExpenseUpdateForm(forms.ModelForm):
    class Meta:
        model = Expense
        exclude = ['created_by']
        
class DebtorUpdateForm(forms.ModelForm):
    class Meta:
        model = Debtor
        exclude = ['created_by']
        
class PaymentUpdateForm(forms.ModelForm):
    class Meta:
        model = Payment
        exclude = ['created_by']
        
class DebtUpdateForm(forms.ModelForm):
    class Meta:
        model = Debt
        exclude = ['created_by','debtor_name','fully_paid','balance','date_cleared']

class OperatorUpdateForm(forms.ModelForm):
    class Meta:
        model = Operator
        exclude = ['operator']

class ContactForm(forms.Form):

    number = forms.IntegerField(required=True)
    message = forms.CharField(widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Send'))
        super(ContactForm, self).__init__(*args, **kwargs)
        
class ExpenseForm(forms.ModelForm):
    date_bought = forms.DateTimeField(widget=DateTimePicker(options={"format": "yyyy-mm-dd hh:mm","pickTime": True}))
                
    class Meta:
        model = Expense
        exclude = ['created_by']

class PayForm(forms.ModelForm):
    class Meta:
        model = Pay
        exclude = ['created_by']

class DebtorForm(forms.ModelForm):
    class Meta:
        model = Debtor
        exclude = ['created_by']

class DebtForm(forms.ModelForm):
    class Meta:
        model = Debt
        exclude = ['created_by','debtor_name','fully_paid','balance','date_cleared']

class PaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        exclude = ['created_by','debt']

transactions/views.py
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.shortcuts import get_object_or_404
from transactions.models import *
from django.core.urlresolvers import reverse
from datetime import datetime, date
import forms
from django.shortcuts import redirect
from django.views.generic import View
from django.db.models import Sum
#new code
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

#Email settings
from django.conf import settings
from django.core.mail import send_mail
from django.views.generic import FormView
from transactions.forms import ContactForm

#Number of records before next page
Paginate = 8


# Create your views here.

class loginmixin(View):
    
    @method_decorator(login_required)
    def dispatch(self,request,*args,**kwargs):
        return super(loginmixin, self).dispatch(request,*args, **kwargs)

class usermixin(View):
        
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.created_by = Operator.objects.get(pk=self.request.user.id)
        self.object = form.save()

        return super(usermixin, self).form_valid(form)

class Index(TemplateView, loginmixin):
    
    template_name = "transactions/index.html"

    
    def get_context_data(self,*args, **kwargs):
        context = super(Index, self).get_context_data(**kwargs)
        period_list = Period.objects.filter(created_by = self.request.user.id)[:5]
        shift_list = Shift.objects.filter(created_by = self.request.user.id)
        expense_list = Expense.objects.filter(created_by = self.request.user.id)[:10]
        total_Earnings = Period.objects.filter(paid=1,created_by = self.request.user.id).aggregate(Sum('period_pay'))
        total_expenses = Expense.objects.filter(created_by = self.request.user.id).aggregate(Sum('item_price'))
       
        for earnings in total_Earnings.values(): 
            for expenses in total_expenses.values():
                if earnings and expenses:
                    net_pay = earnings - expenses
                else:
                    net_pay = 0

        context.update({
            "period_list":period_list,
            "shift_list":shift_list,
            "expense_list":expense_list,
            "total_earnings":total_Earnings,
            "total_expense":total_expenses,
            "net_pay":net_pay,    
        })
        return context

class ContactFormView(FormView, loginmixin):

    form_class = ContactForm
    template_name = "transactions/email_form.html"
    success_url = 'sent/'
    
    def form_valid(self, form):
        message = form.cleaned_data.get('message')
        number = str(form.cleaned_data.get('number'))+'@desksms.appspotmail.com'
            
        send_mail(
            subject="Shifts",
            message=message,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[number],
        )
        print number
        return super(ContactFormView, self).form_valid(form)
    
    def get_initial(self):
        self.period = get_object_or_404(Period, id = self.kwargs.get("pk",None))
        shift_list = Shift.objects.filter(shift_period = self.period, created_by = self.request.user.id)
        message = 'Shifts for ' +str(self.period)
        
        for shift in shift_list:
            message += '\n' +str(shift.shift_location) +' '+ shift.shift_from_date_and_time.strftime("%A %d, %I:%M%p")+' - '+ shift.shift_to_date_and_time.strftime("%H:%M%p") + ' ('+ str(shift.hours_worked_string())+')'
            
        return { 'message': message, 'number':'447979958231' }
    
class EmailSent(TemplateView, loginmixin):
    template_name = "transactions/email_sent.html"

class ShiftList(ListView, loginmixin):
    model = Shift
    paginate_by = Paginate
    
    def get_queryset(self):
        return Shift.objects.filter(created_by = self.request.user.id)

class DebtorList(ListView, loginmixin):
    model = Debtor
    paginate_by = Paginate
       
    def get_context_data(self,*args, **kwargs):
        context = super(DebtorList, self).get_context_data(**kwargs)
        debt_list = Debt.objects.filter(created_by = self.request.user.id)
        debt_owed = debt_list.aggregate(Sum('loan_amount'))
        debt_paid = Payment.objects.filter(debt__in=debt_list).aggregate(Sum('amount'))
        debt_outstanding = debt_list.filter(fully_paid = False).aggregate(Sum('balance'))
        
        
        context.update({
            "debt_list":debt_list,
            "debt_owed":debt_owed,
            "debt_paid":debt_paid,
            "debt_outstanding":debt_outstanding,
        })
        return context
    
    def get_queryset(self):
        return Debtor.objects.filter(created_by = self.request.user.id)
    
class PeriodList(ListView, loginmixin):
    model = Period
    paginate_by = Paginate
    
    def get_queryset(self):
        return Period.objects.filter(created_by = self.request.user.id)
    
class PeriodDetail(DetailView, loginmixin):
    model = Period
    
class DebtorDebt(DetailView, loginmixin):
    model = Debtor 
    paginate_by = Paginate
    template_name = 'transactions/debtor_debt.html'
       
    def get_context_data(self,*args, **kwargs):
        context = super(DebtorDebt, self).get_context_data(**kwargs)
        debt_list = Debt.objects.filter(created_by = self.request.user.id, debtor_name = self.kwargs['pk'])
        debt_owed = debt_list.aggregate(Sum('loan_amount'))
        debt_paid = Payment.objects.filter(debt__in=debt_list).aggregate(Sum('amount'))
        debt_outstanding = debt_list.filter(fully_paid = False).aggregate(Sum('balance'))
        
        
        context.update({
            "debt_list":debt_list,
            "debt_owed":debt_owed,
            "debt_paid":debt_paid,
            "debt_outstanding":debt_outstanding,
        })
        return context

class ShiftDetail(DetailView, loginmixin):
    model = Shift

class DebtDetail(DetailView, loginmixin):
    model = Debt
       
    def get_context_data(self,*args, **kwargs):
        context = super(DebtDetail, self).get_context_data(**kwargs)
        payment_list = Payment.objects.filter(created_by = self.request.user.id, debt = self.kwargs['pk'])
    
        context.update({
            "payment_list":payment_list, 
        })
        return context
    
class PeriodShifts(ListView, loginmixin):
    template_name = 'transactions/shifts_in_period.html'
    
    def get_queryset(self):
        self.period = get_object_or_404(Period, id = self.kwargs.get("periodpk",None))
        return Shift.objects.filter(shift_period = self.period, created_by = self.request.user.id)

class LocationList(ListView, loginmixin):
    model = Location
    paginate_by = Paginate
    queryset = Location.objects.order_by('location_name')

class OperatorList(ListView, loginmixin):
    model = Operator
    paginate_by = Paginate
    
class PayList(ListView, loginmixin):
    model = Pay
    paginate_by = Paginate
    
    def get_queryset(self):
        return Pay.objects.filter(created_by = self.request.user.id)

class ExpenseList(ListView, loginmixin):
    model = Expense
    paginate_by = Paginate
    
    def get_queryset(self):
        return Expense.objects.filter(created_by = self.request.user.id)

class CreateExpense(usermixin, CreateView, loginmixin):
    model = Expense
    form_class = forms.ExpenseForm
    template_name = 'transactions/create_expense.html'
  
    def get_success_url(self):
        return reverse('expense-list')

class CreateLocation(CreateView, loginmixin):
    model = Location
    template_name = 'transactions/create_location.html'
    
    def get_success_url(self):
        return reverse('location-list')
    
class CreateDebtor(usermixin, CreateView, loginmixin):
    model = Debtor
    template_name = 'transactions/create_debtor.html'
    form_class = forms.DebtorForm
    
    def get_success_url(self):
        return reverse('debtor-list')
    
class CreateDebt(CreateView, loginmixin):
    model = Debt
    template_name = 'transactions/create_debt.html'
    form_class = forms.DebtForm
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.created_by = Operator.objects.get(pk=self.request.user.id)
        self.object.debtor_name = Debtor.objects.get(pk=self.kwargs.get('pk'))
        self.object = form.save()
        
        return super(CreateDebt, self).form_valid(form)
           
    def get_context_data(self,*args, **kwargs):
        context = super(CreateDebt, self).get_context_data(**kwargs)
        debtor_id = self.kwargs.get('pk')
    
        context.update({
            "pk":debtor_id,
        })
        return context
    
    def get_initial(self):
        self.debt = Debt()
        content = date.today().strftime("%Y-%m-%d")
         
        return { 'date_loaned': content }
    
    def get_success_url(self):
        return reverse('debtor-debt', args= (self.kwargs.get('pk'),))
    
class CreatePayment(CreateView, loginmixin):
    model = Payment
    template_name = 'transactions/create_payment.html'
    form_class = forms.PaymentForm
    
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.created_by = Operator.objects.get(pk=self.request.user.id)
        self.object.debt = Debt.objects.get(pk=self.kwargs.get('pk'))
        self.object = form.save()
        
        return super(CreatePayment, self).form_valid(form)
           
    def get_context_data(self,*args, **kwargs):
        context = super(CreatePayment, self).get_context_data(**kwargs)
        debt_id = self.kwargs.get('pk')
    
        context.update({
            "pk":debt_id,
        })
        return context 
    
    def get_initial(self):
        self.debt = Debt()
        content = date.today().strftime("%Y-%m-%d")
         
        return { 'date': content }
    
    def get_success_url(self):

templates/transactions/create_debt.html
{% extends "base.html" %}

{% block Title %} Add new debt {% endblock %}

{% block extrahead %}
    <h1>Add Debt</h1>
{% endblock %}

{%block content %}

<div class= "content">
    
    <form action="" method="POST">
      {% csrf_token %}
      <p>
        {{ form.as_p }}
      </p>
      <input style="float: right;" type="submit" class="btn btn-success" value="Save debt" name="save">
    </form>
    
    <div style="text-align: left">
        <form action="{% url "debtor-debt" pk  %}">
            <input type="submit" class="btn btn-info" value="Back to debts">
        </form>
    </div> 
</div>

{% endblock %}

templates/transactions/create_location.html
{% extends "base.html" %}

{% block Title %} Add new location {% endblock %}

{% block extrahead %}
    <h1>Add Location</h1>
{% endblock %}

{%block content %}

<div class= "content">
    
    <form action="{% url "location-new" %}" method="POST">
      {% csrf_token %}
      <p>
        {{ form.as_p }}
      </p>
      <input style="float: right;" type="submit" class="btn btn-success" value="Save location" name="save">
    </form>
    
    <div style="text-align: left">
        <form action="{% url "location-list" %}">
            <input type="submit" class="btn btn-info" value="Back to list">
        </form>
    </div> 
</div>

{% endblock %}

templates/transactions/create_pay.html
{% extends "base.html" %}

{% block Title %} Add new pay {% endblock %}

{% block extrahead %}
    <h1>Add Pay</h1>
{% endblock %}

{%block content %}

<div class= "content">
    
    <form action="{% url "pay-new" %}" method="POST">
      {% csrf_token %}
      <p>
        {{ form.as_p }}
      </p>
      <input style="float: right;" type="submit" class="btn btn-success" value="Save pay" name="save">
    </form>
    
    <div style="text-align: left">
        <form action="{% url "pay-list" %}">
            <input type="submit" class="btn btn-info" value="Back to list">
        </form>
    </div> 
</div>

{% endblock %}

templates/transactions/create_payment.html
{% extends "base.html" %}

{% block Title %} Add new payment {% endblock %}

{% block extrahead %}
    <h1>Add Payment</h1>
{% endblock %}

{%block content %}

<div class= "content">
    
    <form action="" method="POST">
      {% csrf_token %}
      <p>
        {{ form.as_p }}
      </p>
      <input style="float: right;" type="submit" class="btn btn-success" value="Save payment" name="save">
    </form>
    <div style="text-align: left">
        <form action="{% url "debt-detail" pk  %}">
            <input type="submit" class="btn btn-info" value="Back to debt">
        </form>
    </div> 
</div>

{% endblock %}

templates/transactions/create_personnel.html
{% extends "base.html" %}

{% block Title %} Add new personnel {% endblock %}

{% block extrahead %}
    <h1>Add Personnel</h1>
{% endblock %}

{%block content %}

<div class= "content">
    
    <form action="{% url "personnel-new" %}" method="POST">
      {% csrf_token %}
      <p>
        {{ form.as_p }}
      </p>
      <input style="float: right;" type="submit" class="btn btn-success" value="Add personnel" name="save">
    </form>
    
    <div style="text-align: left">
        <form action="{% url "personnel-list" %}">
            <input type="submit" class="btn btn-info" value="Back to list">
        </form>
    </div> 
</div>

{% endblock %}

templates/transactions/debtor_debt.html
{% extends "base.html" %}

{% block Title %} Debtor Details {% endblock %}

{% block extrahead %}
    <h1>{{ debtor.debtor_name|capfirst }}'s Debts</h1>
{% endblock %}

{% block content %}
    
{% regroup debt_list|dictsort:"fully_paid" by fully_paid as debts%}

<div class="content">
    <!--<p><a class="btn btn-success navbar-right" href="{% url "debt-new" debtor.pk %}" role="button">Add debt</a></p>-->
    <div class="well well-sm">
	<span class="glyphicon glyphicon-remove-sign label label-danger" style="font-size: small;" aria-hidden="true"> Borrowed: &#163;{{debt_owed.loan_amount__sum}}</span>
	<span class="glyphicon glyphicon-ok-sign label label-success" style="font-size: small;" aria-hidden="true"> IN: &#163;{{debt_paid.amount__sum}}</span>
	<span class="glyphicon glyphicon-exclamation-sign label label-warning" style="font-size: small;" aria-hidden="true"> OUT: &#163;{{debt_outstanding.balance__sum}}</span>
	<a href="{% url "debt-new" debtor.pk %}" role="button" style="text-decoration: none;"><span class="glyphicon glyphicon-plus label label-success" style="font-size: small;" aria-hidden="true"> Add Debt</a></span>
    </div>
    <div>
        {% for debt in debts %}
                {% if debt.grouper  %}
                    <h3 class="label label-success"><span class="glyphicon glyphicon-ok-circle"></span> Paid debts</h3>
                {% else %}
                    <h3 class="label label-danger"><span class="glyphicon glyphicon-remove-circle"></span> Un-Paid debts</h3>
                {% endif %}
                
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Debts</th>
                            <th>Loan Amount</th>
                            <th>Balance</th>
                            <th>Date Loaned</th>
                            <th colspan="2" style="text-align: center">C.R.U.D</th>
                        </tr>
                    </thead>
                    <tbody>
                   {% for debt in debt.list %}
                        <tr>
                            <td> {{ debt.description|capfirst }} </td>
                            <td> &#163;{{ debt.loan_amount }} </td>
                            <td> &#163;{{ debt.balance }} </td>
                            <td> {{ debt.date_loaned|date:"l, jS M Y" }} </td>
                            <td><a href= "{% url "debt-detail" debt.pk %}">View <span class="glyphicon glyphicon-eye-open"></a></td> 
                            <td><a href= "{% url "debt-update" debt.pk %}"">Update <span class="glyphicon glyphicon-info-sign"></span></a></td> 
                        </tr>
                    {% endfor %}
                    </tbody>
               </table> 
            {% endfor %}
    </div>
</div>
{% endblock %}

templates/transactions/email_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Send period Details{% endblock %}

{% block content %}
    <div class="row">
        <div class="span6">
            <h1>Send period details</h1>
            {% crispy form form.helper %}
        </div>
    </div>
{% endblock %}

{% block more_scripts %}
<script>
        $(function() {
            $('#id_number').focus()            
        });
</script>
{% endblock %}

templates/transactions/expense_list.html
{% extends "base.html" %}

{% block Title %} List of expenses {% endblock %}

{% block extrahead %}
    <h1>Expenses</h1>
{% endblock %}

{%block content %}

{% regroup object_list by date_bought|date:"F, Y" as month%}
    <div class="content">
        <p><a class="btn btn-success navbar-right" href="{% url "expense-new" %}" role="button">Add expense</a></p>
        {% for object_list in month %}
        <h3 class="label label-info"> <span class="glyphicon glyphicon-th-list"></span> Month: {{ object_list.grouper }} </h3>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Date bought</th>
                    <th>Item Description</th>
                    <th>Item Price</th>
                    <th>Item Quant</th>
                    <th>Cost</th>
                    <th>C.R.U.D</th>
                </tr>
            </thead>
            <tbody>
            {% for expense in object_list.list %}
                <tr>
                    <td>{{ expense.date_bought|date:"l jS, P" }}</td>
                    <td>{{ expense.item_description }}</td>
                    <td>&#163;{{ expense.item_price }}</td>
                    <td>{{ expense.item_quantity }}</td>
                    <td>&#163;{{ expense.total_cost }}</td>
                    <td><a href= "/transactions/expense/update/{{ expense.pk }}/">Update</a></td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="3">No Expenses yet.</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {% endfor %}
    </div>

{% endblock %}

templates/transactions/location_list.html
{% extends "base.html" %}

{% block Title %} List of Locations {% endblock %}

{% block extrahead %}
    <h1>Locations</h1>
{% endblock %}

{%block content %}

<div class= "content">
        <p><a class="btn btn-success navbar-right" href="{% url "location-new" %}" role="button">Add location</a></p>
        <span class="glyphicon glyphicon-map-marker"></span>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Address</th>
                    <th style="text-align: center">C.R.U.D</th>
                </tr>
            </thead>
            <tbody>
           {% for location in object_list %}
                <tr>
                    <td>{{ location.location_name }}</td>
                    <td>{{ location.location_address }}</td>
                    <td><a href= "/transactions/location/update/{{ location.pk }}/">Update</a></td>
                </tr>
            {% endfor %}
            </tbody>
       </table>
</div>

{% endblock %}

templates/transactions/operator_list.html
{% extends "base.html" %}

{% block Title %} List of Personnels {% endblock %}

{% block extrahead %}
    <h1>Personnels</h1>
{% endblock %}

{%block content %}

<div class= "content">
    <p><a class="btn btn-success navbar-right" href="{% url "personnel-new" %}" role="button">Add personnel</a></p>
    <span class="glyphicon glyphicon-user"></span>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>Name</th>
                <th>Address</th>
                <th style="text-align: center">C.R.U.D</th>
            </tr>
        </thead>
        <tbody>
       {% for operator in object_list %}
            <tr>
                <td>{{ operator|capfirst }}</td>
                <td>{{ operator.operator_address }}</td>
                <td><a href= "/transactions/personnel/update/{{ operator.pk }}/">Update</a></td>
            </tr>
        {% endfor %}
        </tbody>
   </table>
</div>

{% endblock %}

templates/transactions/period_list.html
{% extends "base.html" %}

{% block Title %} List of periods {% endblock %}

{% block extrahead %}
    <h1>Periods</h1>
{% endblock %}

{%block content %}

{% regroup object_list|dictsort:"paid" by paid as period%}

<div class= "content">
    <p><a class="btn btn-success navbar-right" href="{% url "period-new" %}" role="button">Add period</a></p>
    {% for object_list in period %}
        {% if object_list.grouper  %}
            <h3 class="label label-success"><span class="glyphicon glyphicon-ok-circle"></span> Paid periods</h3>
        {% else %}
            <h3 class="label label-danger"><span class="glyphicon glyphicon-remove-circle"></span> Un-Paid periods</h3>
        {% endif %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Period</th>
                    <th>Number of shifts</th>
                    <th colspan="3" style="text-align: center">C.R.U.D</th>
                </tr>
            </thead>
            <tbody>
           {% for period in object_list.list %}
                <tr>
                    <td>{{ period.period }}</td>
                    <td>{{ period.shifts_this_period }}</td>
                    <td><a href= "{% url "period-shifts" period.pk %}"">View <span class="glyphicon glyphicon-eye-open"></span></a></td>
                    <td><a href= "{% url "period-update" period.pk %}"">Update <span class="glyphicon glyphicon-info-sign"></span></a></td>
                    <td><a href= "{% url "contact-form" period.pk %}"">Send <span class="glyphicon glyphicon-send"></span></a></td>
                </tr>
            {% endfor %}
            </tbody>
       </table>
    {% endfor %}
</div>

{% endblock %}